<?php

use Illuminate\Database\Seeder;

class WoodprojectsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('woodprojects')->delete();
        
        \DB::table('woodprojects')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 8,
                'name' => 'Storage Bench',
                'description' => 'Storage Bench',
                'main_image' => 'bench1_1518614756.jpg',
                'views' => 0,
                'time_invested' => 15,
                'price' => '65',
                'wood_specie_id' => '47',
                'wood_type_id' => '14',
                'width' => '38',
                'depth' => '20',
                'height' => '24',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => '32',
                'finish_sheen_id' => NULL,
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:25:56',
                'updated_at' => '2018-02-14 08:25:56',
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 8,
                'name' => 'Hall Table',
                'description' => 'Hall Table',
                'main_image' => 'hall-table_1518615064.jpg',
                'views' => 0,
                'time_invested' => 12,
                'price' => '50',
                'wood_specie_id' => '47',
                'wood_type_id' => '14',
                'width' => '36',
                'depth' => '20',
                'height' => '30',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:31:04',
                'updated_at' => '2018-02-14 08:31:04',
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 51,
                'name' => 'Candle Box 1',
                'description' => 'Light Brown Candle Box',
                'main_image' => 'candle_box_1_1518615146.jpg',
                'views' => 0,
                'time_invested' => 2,
                'price' => '5',
                'wood_specie_id' => '48',
                'wood_type_id' => '14',
                'width' => '12',
                'depth' => '5',
                'height' => '4',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:32:26',
                'updated_at' => '2018-02-14 08:34:21',
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 51,
                'name' => 'Candle Box 2',
                'description' => 'Dark Brown Candle Box',
                'main_image' => 'candle_box_2_1518615228.jpg',
                'views' => 0,
                'time_invested' => 2,
                'price' => '10',
                'wood_specie_id' => '47',
                'wood_type_id' => '14',
                'width' => '12',
                'depth' => '5',
                'height' => '4',
                'stain_type_id' => '17',
                'stain_color_id' => NULL,
                'stain_sheen_id' => '28',
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:33:49',
                'updated_at' => '2018-02-14 08:33:49',
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 51,
                'name' => 'Candle Holder 1',
                'description' => 'Candle Holder 1',
                'main_image' => 'candle_holder_1_1518615425.jpg',
                'views' => 0,
                'time_invested' => 3,
                'price' => '15',
                'wood_specie_id' => '47',
                'wood_type_id' => '14',
                'width' => '7',
                'depth' => '5',
                'height' => '14',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:37:05',
                'updated_at' => '2018-02-14 08:37:05',
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 51,
                'name' => 'Candle Holder 2',
                'description' => 'Candle Holder 2',
                'main_image' => 'candle_holder_2_1518615485.jpg',
                'views' => 0,
                'time_invested' => 3,
                'price' => '16',
                'wood_specie_id' => '12',
                'wood_type_id' => '14',
                'width' => '7',
                'depth' => '5',
                'height' => '14',
                'stain_type_id' => '17',
                'stain_color_id' => NULL,
                'stain_sheen_id' => '28',
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:38:05',
                'updated_at' => '2018-02-14 08:38:05',
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 50,
                'name' => 'Small Chalkboard',
                'description' => 'Small Chalkboard',
                'main_image' => 'chalkboard_1518615569.jpg',
                'views' => 0,
                'time_invested' => 5,
                'price' => '25',
                'wood_specie_id' => '48',
                'wood_type_id' => '14',
                'width' => '25',
                'depth' => '3',
                'height' => '25',
                'stain_type_id' => '17',
                'stain_color_id' => '11',
                'stain_sheen_id' => '28',
                'finish_type_id' => '34',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:39:29',
                'updated_at' => '2018-02-14 08:39:29',
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 51,
                'name' => 'Mirror',
                'description' => 'Mirror made from reclaimed window',
                'main_image' => 'mirror_1518615642.jpg',
                'views' => 0,
                'time_invested' => 12,
                'price' => '40',
                'wood_specie_id' => '12',
                'wood_type_id' => '14',
                'width' => '23',
                'depth' => '2',
                'height' => '24',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:40:42',
                'updated_at' => '2018-02-14 08:40:42',
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 9,
                'name' => 'Corner Shelf',
                'description' => 'Corner Shelf',
                'main_image' => 'corner_shelf_1518615745.jpg',
                'views' => 0,
                'time_invested' => 4,
                'price' => NULL,
                'wood_specie_id' => '12',
                'wood_type_id' => '14',
                'width' => '6',
                'depth' => '6',
                'height' => '60',
                'stain_type_id' => '17',
                'stain_color_id' => '10',
                'stain_sheen_id' => '28',
                'finish_type_id' => '32',
                'finish_sheen_id' => '53',
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:42:25',
                'updated_at' => '2018-02-14 08:42:25',
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 52,
                'name' => 'Wine Rack',
                'description' => 'Wine Rack can hold 8 bottles',
                'main_image' => 'wine_rack_1518615827.jpg',
                'views' => 0,
                'time_invested' => 4,
                'price' => NULL,
                'wood_specie_id' => '12',
                'wood_type_id' => '14',
                'width' => '8',
                'depth' => '7',
                'height' => '53',
                'stain_type_id' => NULL,
                'stain_color_id' => NULL,
                'stain_sheen_id' => NULL,
                'finish_type_id' => NULL,
                'finish_sheen_id' => NULL,
                'completed_at' => '2018-02-02 00:00:00',
                'weight' => NULL,
                'created_at' => '2018-02-14 08:43:47',
                'updated_at' => '2018-02-14 08:44:10',
            ),
        ));
        
        
    }
}