<div class="row">
	<div class="col-xs-12">
		@if (session('success'))
			<div class="alert alert-success">
				{{ session('success') }}
			</div>
		@endif

		@if (session('error'))
			<div class="alert alert-danger">
				{{ session('error') }}
			</div>
		@endif

		<!-- Display error messages generated by the system -->
		@if (count($errors) > 0)
			<div class="alert alert-danger alert-dismissible" role="alert">
				<strong>Errors:</strong>
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<ul>
					@foreach ($errors->all() as $error)
						<li> {{ $error }} </li>
					@endforeach
				</ul>
			</div>
		@endif
	</div>
</div>