{{-- <div>Dart 1 Total : <span id="d1total">0</span></div>
<input class="d1add" data-amount="1" type="button" value="1" style="" />
<input class="d1add" data-amount="2" type="button" value="2" />
<input class="d1add" data-amount="3" type="button" value="3" />
<input class="d1add" data-amount="4" type="button" value="4" />
<input class="d1add" data-amount="5" type="button" value="5" />
<input class="d1add" data-amount="6" type="button" value="6" />
<input class="d1add" data-amount="7" type="button" value="7" />
<input class="d1add" data-amount="8" type="button" value="8" />
<input class="d1add" data-amount="9" type="button" value="9" />
<input class="d1add" data-amount="10" type="button" value="10" />
<input class="d1add" data-amount="11" type="button" value="11" />
<input class="d1add" data-amount="12" type="button" value="12" />
<input class="d1add" data-amount="13" type="button" value="13" />
<input class="d1add" data-amount="14" type="button" value="14" />
<input class="d1add" data-amount="15" type="button" value="15" />
<input class="d1add" data-amount="16" type="button" value="16" />
<input class="d1add" data-amount="17" type="button" value="17" />
<input class="d1add" data-amount="18" type="button" value="18" />
<input class="d1add" data-amount="19" type="button" value="19" />
<input class="d1add" data-amount="20" type="button" value="20" /> --}}

<div>Dart 2 Total : <span id="d2total">0</span></div>
<input class="d2add" data-amount="1" type="button" value="1" />
<input class="d2add" data-amount="2" type="button" value="2" />
<input class="d2add" data-amount="3" type="button" value="3" />
<input class="d2add" data-amount="4" type="button" value="4" />
<input class="d2add" data-amount="5" type="button" value="5" />
<input class="d2add" data-amount="6" type="button" value="6" />
<input class="d2add" data-amount="7" type="button" value="7" />
<input class="d2add" data-amount="8" type="button" value="8" />
<input class="d2add" data-amount="9" type="button" value="9" />
<input class="d2add" data-amount="10" type="button" value="10" />
<input class="d2add" data-amount="11" type="button" value="11" />
<input class="d2add" data-amount="12" type="button" value="12" />
<input class="d2add" data-amount="13" type="button" value="13" />
<input class="d2add" data-amount="14" type="button" value="14" />
<input class="d2add" data-amount="15" type="button" value="15" />
<input class="d2add" data-amount="16" type="button" value="16" />
<input class="d2add" data-amount="17" type="button" value="17" />
<input class="d2add" data-amount="18" type="button" value="18" />
<input class="d2add" data-amount="19" type="button" value="19" />
<input class="d2add" data-amount="20" type="button" value="20" />

<div>Dart 3 Total : <span id="d3total">0</span></div>
<input class="d3add" data-amount="1" type="button" value="1" />
<input class="d3add" data-amount="2" type="button" value="2" />
<input class="d3add" data-amount="3" type="button" value="3" />
<input class="d3add" data-amount="4" type="button" value="4" />
<input class="d3add" data-amount="5" type="button" value="5" />
<input class="d3add" data-amount="6" type="button" value="6" />
<input class="d3add" data-amount="7" type="button" value="7" />
<input class="d3add" data-amount="8" type="button" value="8" />
<input class="d3add" data-amount="9" type="button" value="9" />
<input class="d3add" data-amount="10" type="button" value="10" />
<input class="d3add" data-amount="11" type="button" value="11" />
<input class="d3add" data-amount="12" type="button" value="12" />
<input class="d3add" data-amount="13" type="button" value="13" />
<input class="d3add" data-amount="14" type="button" value="14" />
<input class="d3add" data-amount="15" type="button" value="15" />
<input class="d3add" data-amount="16" type="button" value="16" />
<input class="d3add" data-amount="17" type="button" value="17" />
<input class="d3add" data-amount="18" type="button" value="18" />
<input class="d3add" data-amount="19" type="button" value="19" />
<input class="d3add" data-amount="20" type="button" value="20" />